contact_links:
  - name: Contribution Guidelines
    url: https://github.com/sauravhathi/coursera-automation-extension/blob/master/guidelines.md
    about: Please read our guidelines before submitting an issue.
  - name: Code of Conduct
    url: https://github.com/sauravhathi/coursera-automation-extension/blob/master/CODE_OF_CONDUCT.md
    about: Please follow our code of conduct when contributing.
  - name: FAQ
    url: https://github.com/sauravhathi/coursera-automation-extension/blob/master/FAQ.md
    about: Check our FAQ for common questions.
