blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/coursera-automation-extension/guidelines.md
    about: Please read our guidelines before submitting an issue.
